/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as EditarperfilRouteImport } from './routes/editarperfil'
import { Route as ActividadesRouteImport } from './routes/actividades'
import { Route as AboutRouteImport } from './routes/about'
import { Route as InicioRouteImport } from './routes/Inicio'
import { Route as IndexRouteImport } from './routes/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarperfilRoute = EditarperfilRouteImport.update({
  id: '/editarperfil',
  path: '/editarperfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesRoute = ActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/Inicio',
  path: '/Inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Inicio': typeof InicioRoute
  '/about': typeof AboutRoute
  '/actividades': typeof ActividadesRoute
  '/editarperfil': typeof EditarperfilRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Inicio': typeof InicioRoute
  '/about': typeof AboutRoute
  '/actividades': typeof ActividadesRoute
  '/editarperfil': typeof EditarperfilRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Inicio': typeof InicioRoute
  '/about': typeof AboutRoute
  '/actividades': typeof ActividadesRoute
  '/editarperfil': typeof EditarperfilRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Inicio'
    | '/about'
    | '/actividades'
    | '/editarperfil'
    | '/profile'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Inicio'
    | '/about'
    | '/actividades'
    | '/editarperfil'
    | '/profile'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/Inicio'
    | '/about'
    | '/actividades'
    | '/editarperfil'
    | '/profile'
    | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InicioRoute: typeof InicioRoute
  AboutRoute: typeof AboutRoute
  ActividadesRoute: typeof ActividadesRoute
  EditarperfilRoute: typeof EditarperfilRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Inicio': {
      id: '/Inicio'
      path: '/Inicio'
      fullPath: '/Inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editarperfil': {
      id: '/editarperfil'
      path: '/editarperfil'
      fullPath: '/editarperfil'
      preLoaderRoute: typeof EditarperfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/Inicio' {
  const createFileRoute: CreateFileRoute<
    '/Inicio',
    FileRoutesByPath['/Inicio']['parentRoute'],
    FileRoutesByPath['/Inicio']['id'],
    FileRoutesByPath['/Inicio']['path'],
    FileRoutesByPath['/Inicio']['fullPath']
  >
}
declare module './routes/about' {
  const createFileRoute: CreateFileRoute<
    '/about',
    FileRoutesByPath['/about']['parentRoute'],
    FileRoutesByPath['/about']['id'],
    FileRoutesByPath['/about']['path'],
    FileRoutesByPath['/about']['fullPath']
  >
}
declare module './routes/actividades' {
  const createFileRoute: CreateFileRoute<
    '/actividades',
    FileRoutesByPath['/actividades']['parentRoute'],
    FileRoutesByPath['/actividades']['id'],
    FileRoutesByPath['/actividades']['path'],
    FileRoutesByPath['/actividades']['fullPath']
  >
}
declare module './routes/editarperfil' {
  const createFileRoute: CreateFileRoute<
    '/editarperfil',
    FileRoutesByPath['/editarperfil']['parentRoute'],
    FileRoutesByPath['/editarperfil']['id'],
    FileRoutesByPath['/editarperfil']['path'],
    FileRoutesByPath['/editarperfil']['fullPath']
  >
}
declare module './routes/profile' {
  const createFileRoute: CreateFileRoute<
    '/profile',
    FileRoutesByPath['/profile']['parentRoute'],
    FileRoutesByPath['/profile']['id'],
    FileRoutesByPath['/profile']['path'],
    FileRoutesByPath['/profile']['fullPath']
  >
}
declare module './routes/register' {
  const createFileRoute: CreateFileRoute<
    '/register',
    FileRoutesByPath['/register']['parentRoute'],
    FileRoutesByPath['/register']['id'],
    FileRoutesByPath['/register']['path'],
    FileRoutesByPath['/register']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InicioRoute: InicioRoute,
  AboutRoute: AboutRoute,
  ActividadesRoute: ActividadesRoute,
  EditarperfilRoute: EditarperfilRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
